development:
  adapter: postgres
  reconnect: false
  database: short_url_development
  pool: 5

test:
  adapter: postgres
  reconnect: false
  database: short_url_test

production:
  adapter: postgres
  reconnect: false
  url: ENV['DATABASE_URL']